export const TOKEN_LOADED = 'token_loaded'
export const ACCOUNT_LOADED = 'account_loaded'

// ui
export const COLUMN_ADD_REQUESTED = 'COLUMN_ADD_REQUESTED'
export const COLUMN_REMOVE_REQUESTED = 'COLUMN_REMOVE_REQUESTED'

export const DIALOG_PUSH_REQUESTED = 'DIALOG_PUSH_REQUESTED'
export const DIALOG_CLOSE_REQUESTED = 'DIALOG_CLOSE_REQUESTED'
export const DIALOG_REPLACE_REQUESTED = 'DIALOG_REPLACE_REQUESTED'
